In [13]:
import pandas as pd
from sklearn import linear_model
import numpy as np

In [14]:
df = pd.read_csv("joined.csv")

In [15]:
df.describe()

,CAMIS,ZIPCODE,SCORE,Latitude,Longitude,Community Board,Council District,Census Tract,BIN,BBL,YEAR,AVERAGE PRICE
count,1.629410e+05,162941.000000,162941.000000,162941.000000,162941.000000,162941.000000,162941.000000,162941.000000,1.620080e+05,1.629410e+05,162941.000000,1.629410e+05
mean,4.614181e+07,10923.100006,12.847927,40.713541,-73.933187,293.245162,26.174038,39549.911710,2.980417e+06,2.880773e+09,2018.079980,2.517361e+06
std,4.388321e+06,542.966680,8.059295,0.064669,0.075925,115.782639,14.486010,33321.484742,1.205230e+06,1.186212e+09,0.896119,3.149801e+06
min,3.019184e+07,10001.000000,-1.000000,40.509115,-74.248416,101.000000,1.000000,100.000000,1.000000e+06,1.000000e+00,2014.000000,3.300000e+05
25%,4.141450e+07,10312.000000,9.000000,40.674179,-73.982760,210.000000,15.000000,11900.000000,2.063479e+06,2.038790e+09,2017.000000,8.471826e+05
50%,5.000626e+07,11211.000000,12.000000,40.716236,-73.946189,307.000000,29.000000,29800.000000,3.112330e+06,3.031550e+09,2018.000000,1.237935e+06
75%,5.005595e+07,11249.000000,13.000000,40.752339,-73.887979,403.000000,37.000000,55300.000000,4.038725e+06,4.014810e+09,2019.000000,2.457562e+06
max,5.010134e+07,12345.000000,98.000000,40.912822,-73.700928,595.000000,51.000000,162100.000000,5.164488e+06,5.080470e+09,2019.000000,1.800000e+07

In [17]:
X = np.array(df["SCORE"]).reshape(-1, 1)
y = np.array(df["AVERAGE PRICE"]).reshape(-1, 1)
print(type(X))

<class 'numpy.ndarray'>

In [18]:
lm = linear_model.LinearRegression()
model = lm.fit(X,y)